import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
    },
    logo: {
        width: 80,
        height: 80,
        marginBottom: 18,
        alignSelf: 'center',
        borderRadius: 20,
        backgroundColor: '#e0fbe6',
    },
    card: {
        width: '100%',
        maxWidth: 400,
        backgroundColor: '#fff',
        borderRadius: 18,
        padding: 24,
        shadowColor: '#22c55e',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.10,
        shadowRadius: 10,
        elevation: 5,
        alignItems: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: '700',
        color: '#14532d',
        marginBottom: 24,
        textAlign: 'center',
    },
    input: {
        height: 48,
        borderWidth: 0,
        borderRadius: 12,
        marginBottom: 16,
        paddingHorizontal: 16,
        backgroundColor: '#f0fdf4',
        fontSize: 16,
        color: '#14532d',
        width: '100%',
    },
    button: {
        backgroundColor: '#22c55e',
        height: 48,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 16,
        shadowColor: '#22c55e',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.18,
        shadowRadius: 6,
        elevation: 2,
        width: '100%',
    },
    buttonText: {
        color: 'white',
        fontSize: 17,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    error: {
        color: '#dc2626',
        marginBottom: 12,
        textAlign: 'center',
    },
    orContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 16,
        width: '100%',
    },
    orLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#e5e7eb',
    },
    orText: {
        marginHorizontal: 12,
        color: '#6b7280',
        fontWeight: '600',
        fontSize: 14,
    },
    socialButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginBottom: 12,
        width: '100%',
        backgroundColor: '#fff',
    },
    socialIcon: {
        width: 22,
        height: 22,
        marginRight: 12,
    },
    socialText: {
        fontSize: 15,
        color: '#222',
        fontWeight: '500',
    },
    backArrow: {
        position: 'absolute',
        left: 16,
        top: 16,
        zIndex: 2,
    },
}); 