import { StyleSheet } from 'react-native';

export const signUpStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
    },
    logo: {
        width: 80,
        height: 80,
        marginBottom: 18,
        alignSelf: 'center',
        borderRadius: 20,
        backgroundColor: '#e0fbe6',
    },
    card: {
        width: '100%',
        maxWidth: 400,
        backgroundColor: 'transparent',
        borderRadius: 0,
        padding: 0,
        shadowColor: 'transparent',
        elevation: 0,
        alignItems: 'center',
    },
    title: {
        fontSize: 24,
        fontWeight: '700',
        color: '#222',
        marginBottom: 24,
        textAlign: 'center',
        fontFamily: 'System',
    },
    row: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    input: {
        height: 56,
        borderWidth: 0,
        borderRadius: 12,
        marginBottom: 16,
        paddingHorizontal: 18,
        backgroundColor: '#e0fbe6',
        fontSize: 16,
        color: '#222',
        width: '100%',
        fontWeight: '500',
        fontFamily: 'System',
    },
    inputHalf: {
        width: '48%',
    },
    button: {
        backgroundColor: '#22c55e',
        height: 56,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 16,
        shadowColor: '#22c55e',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 3,
        width: '100%',
    },
    buttonText: {
        color: 'white',
        fontSize: 17,
        fontWeight: '700',
        letterSpacing: 0.5,
        fontFamily: 'System',
    },
    error: {
        color: '#22c55e',
        marginBottom: 12,
        textAlign: 'center',
        fontWeight: '700',
    },
    orContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 16,
        width: '100%',
    },
    orLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#e5e7eb',
    },
    orText: {
        marginHorizontal: 12,
        color: '#222',
        fontWeight: '700',
        fontSize: 15,
        fontFamily: 'System',
    },
    socialButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 16,
        marginBottom: 12,
        width: '100%',
        backgroundColor: '#fff',
        shadowColor: 'transparent',
    },
    socialIcon: {
        width: 22,
        height: 22,
        marginRight: 12,
    },
    socialText: {
        fontSize: 16,
        color: '#222',
        fontWeight: '500',
        fontFamily: 'System',
    },
    backArrow: {
        position: 'absolute',
        left: 16,
        top: 16,
        zIndex: 2,
        color: '#222',
    },
    link: {
        color: '#22c55e',
        fontWeight: '700',
    },
}); 